In [17]:
import numpy as np
from numpy.linalg import eig
from numpy.linalg import norm
import matplotlib.pyplot as plt

In [114]:
def dimer(u, delta, K, eps, GV, HV):
    n = len(u)
    for k in range(K):
        hu = HV(u)
        va, ve = eig(hu)
        idx = np.argsort(va) 
        va = va[idx]
        ve = ve[:,idx]
        if va[0] < 0 and va[1] > 0 and norm(GV(u)) < eps:
            print("OK")
            return u
        elif va[0] > 0:
            print(va[0])
            return None
        else:
            v1 = np.array([ve[0]])
            u = u - delta * (np.identity(n) - 2*np.transpose(v1).dot(v1)).dot(GV(u))
            print(u)
            print("")
    return None

In [121]:
delta = 0.001
K = 1000
eps = 0.01

In [122]:
def V1(u):
    x = u[0][0]
    y = u[0][1]
    return ((x-1)**2 + y**2) * ((x+1)**2 + y**2)

def GV1(u):
    x = u[0][0]
    y = u[0][1]
    return np.array([2*(x-1)*((x+1)**2 + y**2) + 2*(x+1)*((x-1)**2 + y**2), 2*y*((x+1)**2 + y**2) + 2*y*((x-1)**2 + y**2)])

def HV1(u):
    x = u[0][0]
    y = u[0][1]
    return np.array([[2*((x+1)**2 + y**2 + (x-1)**2 + y**2 + 4*(x-1)*(x+1)), 8*y*x],
                    [8*y*x, 4*((x**2+1) + 3*y**2)]])

u1 = np.array([[0.2, -0.3]])

In [142]:
def V2(u):
    x = u[0][0]
    y = u[0][1]
    return x**4 - 2*x**2 + y**4 - 2*y**2

def GV2(u):
    x = u[0][0]
    y = u[0][1]
    return np.array([4*(x**3 - x), 4*(y**3 - y)])

def HV2(u):
    x = u[0][0]
    y = u[0][1]
    return np.array([[4*(3*x - 1), 0],
                    [0, 4*(3*y - 1)]])

u2 = np.array([[0.001, 0]])

In [143]:
def V3(u):
    x = u[0][0]
    y = u[0][1]
    return (1-x**2-y**2)**2 + y**2/(x**2+y**2)

def GV3(u):
    x = u[0][0]
    y = u[0][1]
    return np.array([-4*x*(1-x**2-y**2) - 2*x*y**2/(x**2+y**2)**2, -4*y*(1-x**2-y**2) + 2*y*x**2/(x**2+y**2)**2])

def HV3(u):
    x = u[0][0]
    y = u[0][1]
    return np.array([[8*x**2 - 4*(1-x**2-y**2) - 2*y**2/(x**2+y**2)**2 + 8*x**2*y**2/(x**2+y**2)**3, 8*x*y - 4*x*y/(x**2+y**2)**2 + 8*x*y**3/(x**2+y**2)**3],
                    [8*x*y - 4*x*y/(x**2+y**2)**2 + 8*x*y**3/(x**2+y**2)**3, 8*y**2 - 4*(1-x**2-y**2) + 2*x**2/(x**2+y**2)**2 - 8*x**2*y**2/(x**2+y**2)**3]])

u3 = np.array([[0.2, 0]])

In [144]:
def V4(u):
    x = u[0][0]
    y = u[0][1]
    z = u[0][2]
    v = (x**2+y**2)*0.25 + y
    return 10*u**2*(u**2-1) + 0.07*x**2 + y**2 + 15/(19*np.sqrt(19))*z**2

In [145]:
print(dimer(u2, delta, K, eps, GV2, HV2))

[[1.004000e-03 3.999996e-06]]

[[1.00803199e-03 7.99999195e-06]]

[[1.01209612e-03 1.20001159e-05]]

[[1.01619250e-03 1.60004957e-05]]

[[1.02032126e-03 2.00012595e-05]]

[[1.02448255e-03 2.40025353e-05]]

[[1.02867649e-03 2.80044510e-05]]

[[1.03290321e-03 3.20071348e-05]]

[[1.03716284e-03 3.60107147e-05]]

[[1.04145553e-03 4.00153188e-05]]

[[1.04578141e-03 4.40210751e-05]]

[[1.05014062e-03 4.80281119e-05]]

[[1.05453329e-03 5.20365572e-05]]

[[1.05895956e-03 5.60465395e-05]]

[[1.06341958e-03 6.00581868e-05]]

[[1.06791349e-03 6.40716276e-05]]

[[1.07244142e-03 6.80869901e-05]]

[[1.07700353e-03 7.21044029e-05]]

[[1.08159996e-03 7.61239945e-05]]

[[1.08623085e-03 8.01458933e-05]]

[[1.09089635e-03 8.41702280e-05]]

[[1.09559661e-03 8.81971273e-05]]

[[1.10033178e-03 9.22267199e-05]]

[[1.10510201e-03 9.62591349e-05]]

[[0.00110991 0.00010029]]

[[0.00111475 0.00010433]]

[[0.00111962 0.00010837]]

[[0.00112454 0.00011242]]

[[0.00112948 0.00011647]]

[[0.00113447 0.00012052]]

[[

[[0.01736031 0.0071704 ]]

[[0.01745841 0.00721114]]

[[0.01755706 0.00725211]]

[[0.01765628 0.00729331]]

[[0.01775605 0.00733474]]

[[0.01785639 0.0073764 ]]

[[0.0179573 0.0074183]]

[[0.01805878 0.00746044]]

[[0.01816083 0.00750281]]

[[0.01826346 0.00754542]]

[[0.01836667 0.00758827]]

[[0.01847046 0.00763136]]

[[0.01857484 0.00767469]]

[[0.01867981 0.00771827]]

[[0.01878537 0.00776209]]

[[0.01889154 0.00780616]]

[[0.0189983  0.00785048]]

[[0.01910566 0.00789504]]

[[0.01921364 0.00793986]]

[[0.01932222 0.00798493]]

[[0.01943142 0.00803025]]

[[0.01954123 0.00807583]]

[[0.01965167 0.00812166]]

[[0.01976273 0.00816775]]

[[0.01987442 0.0082141 ]]

[[0.01998674 0.00826072]]

[[0.02009969 0.00830759]]

[[0.02021329 0.00835473]]

[[0.02032753 0.00840213]]

[[0.02044241 0.0084498 ]]

[[0.02055794 0.00849774]]

[[0.02067413 0.00854595]]

[[0.02079097 0.00859443]]

[[0.02090847 0.00864318]]

[[0.02102664 0.00869221]]

[[0.02114547 0.00874151]]

[[0.02126498 0.00879109]]

[[0